/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Mac Color Picker
 #	author : miyako
 #	2015/10/16
 #
 # --------------------------------------------------------------------------------*/



// --- Mac Color Picker
void Mac_Select_RGB_color(sLONG_PTR *pResult, PackagePtr pParams);

void OnStartup();

#ifndef NSAppKitVersionNumber10_10_Max
#define NSAppKitVersionNumber10_10_Max 1349
#endif